name: Deploy Static Website

on:
 workflow_dispatch:   # this allows manual trigger

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Optional: you could run a build step if you had one
      # For pure HTML, this is not needed
      # - name: Build site
      #   run: echo "Nothing to build for static HTML"

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            index.html
            css/
            js/
            images/
            fonts/
