name: Deploy Static Website

on:
  workflow_dispatch:   # allows manual trigger

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Upload your static website as an artifact
      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            index.html
            css/
            js/
            images/
            fonts/
