name: CI/CD Docker Deploy

on:
 workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # <--- use your VM runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop old container
        run: |
          if [ $(docker ps -q -f name=web-deploy-container) ]; then
            docker stop web-deploy-container
            docker rm web-deploy-container
          fi || echo "No existing container"

      - name: Build Docker image
        run: docker build -t web-deploy-image1 .

      - name: Run Docker container
        run: docker run -d -p 8000:80 --name web-deploy-container web-deploy-image1
